# Generated by Django 6.0.7 on 2026-07-28 09:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('doctor', '0001_initial'),
        ('patient', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appointment_date', models.DateField(db_index=True)),
                ('start_time', models.TimeField()),
                ('slot_duration', models.PositiveSmallIntegerField(default=30)),
                ('status', models.CharField(choices=[('BOOKED', 'Booked'), ('CANCELLED', 'Cancelled'), ('COMPLETED', 'Completed'), ('NO_SHOW', 'No Show')], db_index=True, default='BOOKED', max_length=20)),
                ('cancellation_reason', models.TextField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='appointments', to='doctor.doctor')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='appointments', to='patient.patient')),
            ],
            options={
                'db_table': 'appointments',
                'ordering': ['appointment_date', 'start_time'],
                'indexes': [models.Index(fields=['doctor', 'appointment_date', 'status'], name='appointment_doctor__889281_idx'), models.Index(fields=['patient', 'appointment_date'], name='appointment_patient_ee8848_idx'), models.Index(fields=['appointment_date', 'status'], name='appointment_appoint_b9472b_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('status', 'BOOKED')), fields=('doctor', 'appointment_date', 'start_time'), name='unique_active_doctor_slot')],
            },
        ),
    ]
