# Generated by Django 6.0.7 on 2026-07-26 19:35

import datetime
import django.core.validators
import django.db.models.deletion
import phonenumber_field.modelfields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clinic', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Specialization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Specialization',
                'verbose_name_plural': 'Specializations',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.CharField(choices=[('MALE', 'Male'), ('FEMALE', 'Female'), ('OTHER', 'Other')], max_length=10)),
                ('date_of_birth', models.DateField(validators=[django.core.validators.MinValueValidator(limit_value=datetime.date(1900, 1, 1), message='Date of birth cannot be before 1900')])),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region='KE')),
                ('license_number', models.CharField(help_text='Medical board registration/license number', max_length=100, unique=True)),
                ('qualification', models.CharField(blank=True, help_text='e.g. MBChB, MD, BDS', max_length=150)),
                ('years_of_experience', models.PositiveIntegerField(default=0)),
                ('employment_type', models.CharField(choices=[('FULL_TIME', 'Full Time'), ('PART_TIME', 'Part Time'), ('VISITING', 'Visiting Consultant')], default='FULL_TIME', max_length=20)),
                ('bio', models.TextField(blank=True)),
                ('profile_photo', models.ImageField(blank=True, null=True, upload_to='doctors/')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this doctor is currently practicing')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('clinic', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='doctors', to='clinic.clinic')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='doctor_profile', to=settings.AUTH_USER_MODEL)),
                ('specialization', models.ForeignKey(help_text='Medical specialization', on_delete=django.db.models.deletion.PROTECT, related_name='doctors', to='doctor.specialization')),
            ],
            options={
                'ordering': ['user__last_name', 'user__first_name'],
                'indexes': [models.Index(fields=['specialization'], name='doctor_doct_special_2c6c5a_idx'), models.Index(fields=['clinic'], name='doctor_doct_clinic__919c81_idx'), models.Index(fields=['is_active'], name='doctor_doct_is_acti_c8f073_idx')],
                'constraints': [models.UniqueConstraint(fields=('license_number', 'clinic'), name='unique_license_per_clinic')],
            },
        ),
    ]
